[server]
maxUploadSize = 20

[theme]
primaryColor = "#117A63"
backgroundColor = "#F1F6F3"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#17352D"
font = "sans serif"

[browser]
gatherUsageStats = false
